package com.example.demo.model;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_baseinf.book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_baseinf.book_title
     *
     * @mbggenerated
     */
    private String bookTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_baseinf.book_publishment
     *
     * @mbggenerated
     */
    private String bookPublishment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_baseinf.book_neworold
     *
     * @mbggenerated
     */
    private String bookNeworold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_baseinf.book_author
     *
     * @mbggenerated
     */
    private String bookAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_baseinf.book_img
     *
     * @mbggenerated
     */
    private String bookImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_baseinf
     *
     * @mbggenerated
     */
    public Book(Integer bookId, String bookTitle, String bookPublishment, String bookNeworold, String bookAuthor, String bookImg) {
        this.bookId = bookId;
        this.bookTitle = bookTitle;
        this.bookPublishment = bookPublishment;
        this.bookNeworold = bookNeworold;
        this.bookAuthor = bookAuthor;
        this.bookImg = bookImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_baseinf
     *
     * @mbggenerated
     */
    public Book() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_baseinf.book_id
     *
     * @return the value of book_baseinf.book_id
     *
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_baseinf.book_id
     *
     * @param bookId the value for book_baseinf.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_baseinf.book_title
     *
     * @return the value of book_baseinf.book_title
     *
     * @mbggenerated
     */
    public String getBookTitle() {
        return bookTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_baseinf.book_title
     *
     * @param bookTitle the value for book_baseinf.book_title
     *
     * @mbggenerated
     */
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle == null ? null : bookTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_baseinf.book_publishment
     *
     * @return the value of book_baseinf.book_publishment
     *
     * @mbggenerated
     */
    public String getBookPublishment() {
        return bookPublishment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_baseinf.book_publishment
     *
     * @param bookPublishment the value for book_baseinf.book_publishment
     *
     * @mbggenerated
     */
    public void setBookPublishment(String bookPublishment) {
        this.bookPublishment = bookPublishment == null ? null : bookPublishment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_baseinf.book_neworold
     *
     * @return the value of book_baseinf.book_neworold
     *
     * @mbggenerated
     */
    public String getBookNeworold() {
        return bookNeworold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_baseinf.book_neworold
     *
     * @param bookNeworold the value for book_baseinf.book_neworold
     *
     * @mbggenerated
     */
    public void setBookNeworold(String bookNeworold) {
        this.bookNeworold = bookNeworold == null ? null : bookNeworold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_baseinf.book_author
     *
     * @return the value of book_baseinf.book_author
     *
     * @mbggenerated
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_baseinf.book_author
     *
     * @param bookAuthor the value for book_baseinf.book_author
     *
     * @mbggenerated
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_baseinf.book_img
     *
     * @return the value of book_baseinf.book_img
     *
     * @mbggenerated
     */
    public String getBookImg() {
        return bookImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_baseinf.book_img
     *
     * @param bookImg the value for book_baseinf.book_img
     *
     * @mbggenerated
     */
    public void setBookImg(String bookImg) {
        this.bookImg = bookImg == null ? null : bookImg.trim();
    }
}