package com.example.demo.mapper;

import com.example.demo.model.UserBaseInf;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserBaseInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_baseinf",
        "where user_email = #{userEmail,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userEmail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_baseinf (user_email, user_name, ",
        "user_telephone, user_address, ",
        "user_good, user_trust, ",
        "role, lastPasswordResetDate, ",
        "user_password)",
        "values (#{userEmail,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{userTelephone,jdbcType=VARCHAR}, #{userAddress,jdbcType=VARCHAR}, ",
        "#{userGood,jdbcType=DOUBLE}, #{userTrust,jdbcType=DOUBLE}, ",
        "#{role,jdbcType=VARCHAR}, #{lastpasswordresetdate,jdbcType=DATE}, ",
        "#{userPassword,jdbcType=LONGVARCHAR})"
    })
    int insert(UserBaseInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    int insertSelective(UserBaseInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "user_email, user_name, user_telephone, user_address, user_good, user_trust, ",
        "role, lastPasswordResetDate, user_password",
        "from user_baseinf",
        "where user_email = #{userEmail,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    UserBaseInf selectByPrimaryKey(String userEmail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBaseInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    @Update({
        "update user_baseinf",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "user_telephone = #{userTelephone,jdbcType=VARCHAR},",
          "user_address = #{userAddress,jdbcType=VARCHAR},",
          "user_good = #{userGood,jdbcType=DOUBLE},",
          "user_trust = #{userTrust,jdbcType=DOUBLE},",
          "role = #{role,jdbcType=VARCHAR},",
          "lastPasswordResetDate = #{lastpasswordresetdate,jdbcType=DATE},",
          "user_password = #{userPassword,jdbcType=LONGVARCHAR}",
        "where user_email = #{userEmail,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(UserBaseInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_baseinf
     *
     * @mbggenerated
     */
    @Update({
        "update user_baseinf",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "user_telephone = #{userTelephone,jdbcType=VARCHAR},",
          "user_address = #{userAddress,jdbcType=VARCHAR},",
          "user_good = #{userGood,jdbcType=DOUBLE},",
          "user_trust = #{userTrust,jdbcType=DOUBLE},",
          "role = #{role,jdbcType=VARCHAR},",
          "lastPasswordResetDate = #{lastpasswordresetdate,jdbcType=DATE}",
        "where user_email = #{userEmail,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserBaseInf record);
}